# Generated by Django 3.2 on 2021-04-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_classifier', '0002_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='prediction',
            new_name='prediction_label',
        ),
        migrations.AddField(
            model_name='image',
            name='prediction_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='img_classifier/'),
        ),
    ]
