# Generated by Django 3.2 on 2021-05-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_classifier', '0003_auto_20210421_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img_classifier/'),
        ),
    ]
